/// The `Opcode` type.
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum Opcode {
    // Basic opcodes
    Inc, // +
    IncPtr, // >
    Dec, // -
    DecPtr, // <
    Double, // *
    Halve, // /
    Print, // .
    Read, // ,
    Push, // :
    Pop, // ;
    JzCell, // [
    JnzCell, // ]
    JzStack, // (
    JnzStack, // )
    JmpStack, // ^
    Dup, // &
    Swap, // \
    Count, // #
    Compare, // =
    Str, // "
    Break, // !
    BinMod, // b
    ChrMod, // c
    IntMod, // i
    HexMod, // x
    Terminate, // q

    // Opcodes generated by the optimizer
    Clear,
}
