language: rust
rust: stable
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: 1epbUMCdh7u+/qwll3A6kvDVMAzD2YcxZ3mPcKEGkLUCew0iCzE66+KsvJu5JEccb/y/wDxcdnecnDQSwmWMFNjwbbR980HKeOTtJD2f6sCfIRgdbz5915TY5i82pqpGpwA9kbBluU6ZuAgeI+3XK2gDPmHdIlw/aVFgpkSt1QMxzYetqM+MYpFJ7F6+U7LetDKothtocB+SbhzzK0LY4mYv28B587Wi2zUKZ0BtHl2LVbFk1ViGhvQbnpyjaT0l23KwL1R2O9+r4qk9HWlKOnC1DhCb1dB56UnqzM2d29EhUmreyILuRs+uzI55+gzmau+gA6uAmqFUcdXGrkaI2HAq+nchnwEF6ys+haztVqvlnPko+oyUdVjhY0mXdW1AMzfdTXAlwJsEI7oNyBead3YYUSvGu6kRzzkh3FThpId+jgdmw/+DBOJoJih3AqC0t50pBV7BYVdaVAtewQvrwFnRePfi6YaPvqh4hFTVUXpLo9tjwosId6JMrodatcAdwAR4rYOl1uHUPWR+J0QbcNWV8B18lrtZZUpmPAD7gQHkRwfNJz/d1X0JkBQNhUaaiv62nf9o+S/kA6Ysl7NAU89kQvjurA30+R0DMpAME/wSQrPQxhkXjn42Cw7j25uyfUpZMUW4Urq08bEnl186moPI1TMETuiAWSduKMWKwLY=
